[package]
name = "mu-rs"
version = "0.1.0"
authors = ["Xannden <Xannden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.1.0"
select = "0.5"
thiserror = "1.0.24"
